### ISSUE TITLE
Error occurred when enabling CPU Feature Buffer

### ISSUE THREAD

**Issue by starry12** [jeongminpark417/GIDS#15]
Hi,

I tried to test the performance of DGL+BAM and GIDS on the IGB-small dataset.
I used the following command to load the feature data:
```CUDA_VISIBLE_DEVICES=4 python tensor_write.py --path /home/embed/Documents/GIDS_before_2/datasets/small/processed/paper/node_feat.npy  --cache_size $((4*1024)) --num_ssd 1   --num_ele $((4*1000*1000*1024)) --page_size 4096 --ssd_list 0```

Then I ran the following command to test DGL+BAM and it showed no problem"
```sudo CUDA_VISIBLE_DEVICES=4  python homogenous_train.py --dataset_size small --path /home/embed/Documents/GIDS_before_2/datasets/   --epochs 1 --log_every 1000 --uva_graph 1 --GIDS --batch_size 1024  --data IGB --model_type sage --num_layers 3 --fan_out '10,5,5' --cache_size $((4*1024)) --num_ssd 1   --num_ele $((4*1000*1000*1024)) --page_size 4096 --emb_size 1024 ```

I tried to add GIDS optimization techniques on top of this. I tested accumulator and GPU window buffer without any issues.
For reference, here are the results:
![result1](https://github.com/jeongminpark417/GIDS/assets/33948375/c420b40a-d61b-4903-9f9f-e95dae42abb8)

However, once I add the CPU buffer technique, errors will occur:
![result2](https://github.com/jeongminpark417/GIDS/assets/33948375/6462e9d8-4475-49d7-af68-807b4571e008)

I think the reason is an illegal memory access during the attempt to pin the graph to memory (pin_memory_).
Do you have any ideas or solutions for this error? Thanks.

For reference, I used a v100 with 32GB RAM and an intel NVMe SSD.
I generated the pr_small.pt file with the following command:
```sudo CUDA_VISIBLE_DEVICES=4  python page_rank_node_list_gen.py --dataset_size small --path /home/embed/Documents/GIDS_before_2/datasets/ --out_path ./pr_small.pt  --data IGB```

**Comment by WWWzq-01** [comment]
The issue is associated with line 458 of `gids_nvme.cu`, which involves the function `BAM_Feature_Store<TYPE>::set_cpu_buffer`. This corresponds to the `set_cpu_buffer` function in GIDS.py:
```python
    def set_cpu_buffer(self, ten, N):
        topk_ten = ten[:N]
        topk_len = len(topk_ten)
        d_ten = topk_ten.to(self.gids_device)
        self.BAM_FS.set_cpu_buffer(d_ten.data_ptr(), topk_len)
```
Subsequently, line 63 in the code calls set_cpu_buffer as follows: `GIDS_Loader.set_cpu_buffer(pr_ten, num_pinned_nodes)`. Therefore, it appears that the problem might be related to pr_small.pt.

**Comment by jeongminpark417** [comment]
It seems like pr_small.pt is not correctly created. Based on the log, the node ID requested from the kernel to CPU memory buffer is beyond CPU memory capacity, which is initialized with pr_small.pt file. Can you share the flags that you used to create pr_small.pt file?

**Comment by starry12** [comment]
hi, thanks both for your responses.

I generated the pr_small.pt file with the following command:
> sudo CUDA_VISIBLE_DEVICES=4  python page_rank_node_list_gen.py --dataset_size small --path /home/embed/Documents/GIDS_before_2/datasets/  --out_path ./pr_small.pt   --data IGB

output:
![pr_output](https://github.com/jeongminpark417/GIDS/assets/33948375/d7177923-a87a-40d1-a49b-9e26c521f1b8)

The size of the generated pt file is ~4MB. Is this size wrong?

**Comment by jeongminpark417** [comment]
It seems like you did not add the path to your pin_file when you run the trainging code. Add pr_small.pt path to the flag `--pin_file`.

**Comment by starry12** [comment]
hi, thank u for your follow-up on this issue.
Sadly, I haven't solved it yet.

I added the _pin_file_ flag and ran the following command to test:
```
sudo CUDA_VISIBLE_DEVICES=4  python homogenous_train.py --pin_file /home/embed/Documents/GIDS/evaluation/pr_small.pt  --dataset_size small --path /home/embed/Documents/GIDS_before_2/datasets/ --epochs 1 --log_every 1000 --uva_graph 1 --GIDS --batch_size 1024  --data IGB --model_type sage --num_layers 3 --fan_out '10,5,5' --cache_size $((4*1024)) --num_ssd 1   --num_ele $((4*1000*1000*1024)) --page_size 4096 --emb_size 1024 --window_buffer --wb_size 8   --cpu_buffer --cpu_buffer_percent 0.2   --accumulator
```
The same error still occurs:


To check that the pt file was read correctly, I output the data from the following code in _homogenous_train.py:_
```python
if(args.cpu_buffer):
        num_nodes = g.number_of_nodes()  # 1000000
        num_pinned_nodes = int(num_nodes * args.cpu_buffer_percent) # 1000000 * 0.2 = 200000
        GIDS_Loader.cpu_backing_buffer(dim, num_pinned_nodes)
        pr_ten = torch.load(args.pin_file)
        GIDS_Loader.set_cpu_buffer(pr_ten, num_pinned_nodes)
```
result:
```
num_pinned_nodes:  200000
args.pin_file:  /home/embed/Documents/GIDS/evaluation/pr_small.pt
pr_ten:  tensor([178063, 873969, 509510,  ..., 450454, 955360, 773788])
```

Also, I output the data from the following code in _GIDS.py_ :
```python
def set_cpu_buffer(self, ten, N):
        topk_ten = ten[:N]
        topk_len = len(topk_ten)
        d_ten = topk_ten.to(self.gids_device)
        self.BAM_FS.set_cpu_buffer(d_ten.data_ptr(), topk_len)
```
result:
```
topk_ten:  tensor([178063, 873969, 509510,  ..., 741573, 142574, 150302])
topk_len:  200000
d_ten.data_ptr():  139942026018816
```

The problem occurs in the following code snippet in the _gids_nvme.cu_,  and more specifically **set_cpu_buffer_kernel** :
```CUDA
template <typename TYPE>
void  BAM_Feature_Store<TYPE>::set_cpu_buffer(uint64_t idx_buffer, int num){
  int bsize = 1024;
  int grid = (num + bsize - 1) / bsize;
  uint64_t* idx_ptr = (uint64_t* ) idx_buffer;
  set_cpu_buffer_kernel<TYPE><<<grid,bsize>>>(d_range, idx_ptr, num, pageSize);
  cuda_err_chk(cudaDeviceSynchronize());
  // __global__ void set_cpu_buffer_data_kernel(array_d_t<T> *dr, GIDS_CPU_buffer<T> CPU_buffer, uint64_t* idx_ptr, uint64_t dim, int num) {
  set_cpu_buffer_data_kernel<TYPE><<<(num),bsize>>>(a->d_array_ptr, CPU_buffer, idx_ptr, dim, num);
  cuda_err_chk(cudaDeviceSynchronize());

  seq_flag = false;

}
```

But I still don't know what is causing this problem. Do you have any insights about this issue?
Thanks again!

**Comment by smallgrape14** [comment]
@starry12 ，Has this problem been solved ? 
I run the following command to test GIDS:
` CUDA_VISIBLE_DEVICES=0  python heterogeneous_train.py --path /datasets/igb_datasets/   --dataset_size small --epochs 1 --log_every 1000 --uva_graph 1 --GIDS --batch_size 1024  --data IGB --model_type rsage --num_layers 3 --fan_out '10,5,5' --cache_size $((4*1024)) --num_ssd 1   --num_ele $((4*1000*1000*1024)) --page_size 4096 --emb_size 1024 --window_buffer --wb_size 8   --cpu_buffer --cpu_buffer_percent 0.2   --accumulator --pin_file pr_full.pt --offset 128`
I also encountered a similar problem：
![image](https://github.com/jeongminpark417/GIDS/assets/60038680/59cc1463-1e21-48f4-a968-58a0b616bdac)

PS: I also use a v100 with 32GB RAM and an intel optane NVMe SSD.

**Comment by starry12** [comment]
@smallgrape14  hi, I haven't solved the problem yet.

I tried to solve it from the environmental.

This is my environment:
OS: Ubuntu 20.04.6, Kernel 5.4.0-99-generic
NVIDIA Driver: 545.23.08, CUDA Versions: 12.3, GPU name: NVIDIA V100-PCIE-32GB
SSD used: Intel SSD D7-P5520 SERIES

Can you send me your environment for comparison?

**Comment by starry12** [comment]
As a supplement, pytorch version is 2.3.0 and dgl version is 2.2.1+cu121.

**Comment by smallgrape14** [comment]
My environment is :
OS: Ubuntu 20.04.6, Kernel 5.8.10-050810-generic
NVIDIA Driver: 550.54.15, CUDA Versions: 12.4, 
GPU name: NVIDIA V100-PCIE-32GB
SSD used: Intel SSD optane  P5800 SERIES
pytorch version is 2.2.1 and dgl version is 2.1.0+cu121.

**Comment by jeongminpark417** [comment]
Hi, sorry for the late response. Will it be possible to share your pr_small.pt file with me by sending it to jeongminpark17@gmail.com?

**Comment by starry12** [comment]
@jeongminpark417 
Hi, Thank you very much for taking the time to help solve the problem. I have sent the file to u.

**Comment by jeongminpark417** [comment]
Hello, 
I tested your file, and it works on our system. Upon closer inspection of the log, it appears that the CPU memory size is insufficient to use the CPU feature buffer. GIDS pins the graph structure data, which is typically around 5% of the total graph size. Therefore, 32GB is not large enough to enable the Constant Buffer.
